name: Update API Spec

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  download-commit-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Download profile api spec
        run: curl -o api-spec/profile-apis.json https://develop.battle.net/api/pages/content/documentation/world-of-warcraft/profile-apis.json

      - name: Download retail game data api spec
        run: curl -o api-spec/retail-game-data-apis.json https://develop.battle.net/api/pages/content/documentation/world-of-warcraft/game-data-apis.json

      - name: Download classic game data api spec
        run: curl -o api-spec/classic-game-data-apis.json https://develop.battle.net/api/pages/content/documentation/world-of-warcraft-classic/game-data-apis.json

      - name: Detect changes
        id: changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then 
            echo ::set-output name=changed::0
          else 
            echo ::set-output name=changed::1
          fi

      - name: Generate api source code
        if: steps.changes.outputs.changed == 1
        run: |
          go generate ./...

      - name: Commit and push file changes
        if: steps.changes.outputs.changed == 1
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b bot/spec-api-update
          git add api-spec/profile-apis.json api-spec/retail-game-data-apis.json api-spec/classic-game-data-apis.json
          git commit -m "Update api-spec"
          git push -f origin bot/spec-api-update
      
      - name: Create pull request
        if: steps.changes.outputs.changed == 1
        run: |
          gh pr create --title "Update api-spec" --body "Update api-spec" --base main --head bot/spec-api-update
        env:
          GH_TOKEN: ${{ github.token }}